/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import databaseUtil.DataBaseConnector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Persoon;
/**
 *
 * @author Method
 */
public class WijzigPersoon extends javax.swing.JFrame {
    PersoonFrame persoonFrame;
    Persoon persoon;
    /**
     * Creates new form WijzigPersoon
     */
    public WijzigPersoon(Persoon persoon, PersoonFrame persoonFrame) {
        initComponents();
        this.setTitle("Persoon wijzigen");
        this.persoonFrame = persoonFrame;
        this.persoon = persoon;
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        vulInvoerVelden();
    }
    
    private void vulInvoerVelden() {
        this.txfVoornaam.setText(persoon.getVoornaam());
        this.txfTussenvoegsel.setText(persoon.getTussenvoegsel());
        this.txfAchternaam.setText(persoon.getAchternaam());
        this.txfWoonplaats.setText(persoon.getWoonplaats());
        this.txfStraatnaam.setText(persoon.getStraatnaam());
        this.txfHuisnummer.setText(persoon.getHuisnummer());
    }
    
    // Wijzig persoon Gegevens
    private void wijzigPersoonGegevens() {
        String Voornaam = this.txfVoornaam.getText();
        String Tussenvoegsel = this.txfTussenvoegsel.getText();
        String Achternaam = this.txfAchternaam.getText();
        String Woonplaats = this.txfWoonplaats.getText();
        String Straatnaam = this.txfStraatnaam.getText();
        String Huisnummer = this.txfHuisnummer.getText();

        try {
            Connection conn = DataBaseConnector.getConnection();
            Statement stat = conn.createStatement();

            String prepStatWijzigPersoon = "UPDATE Persoon SET voornaam=?,"
                    + "tussenvoegsel=?, achternaam=? WHERE persoon.id = ?";
            PreparedStatement prepStat = conn.prepareStatement(prepStatWijzigPersoon);

            prepStat.setString(1, Voornaam);
            prepStat.setString(2, Tussenvoegsel);
            prepStat.setString(3, Achternaam);
            prepStat.setString(4, persoon.getId());

            prepStat.executeUpdate();

            stat.close();

        } catch (SQLException exc) {
            JOptionPane.showMessageDialog(this, "Wijzigingen voor persoon niet opgeslagen\n" + exc.toString());
        }
    }
    // Wijzig Klant gegevens
    private void wijzigKlantGegevens() {
        String Woonplaats = this.txfWoonplaats.getText();
        String Straatnaam = this.txfStraatnaam.getText();
        int Huisnummer = Integer.parseInt(this.txfHuisnummer.getText());

        try {
            Connection conn = DataBaseConnector.getConnection();
            Statement stat = conn.createStatement();

            String prepStatWijzigPersoon = "UPDATE Klant SET woonplaats=?,"
                    + "straatnaam=?, huisnummer=? WHERE persoon_id = ?";
            PreparedStatement prepStat = conn.prepareStatement(prepStatWijzigPersoon);

            prepStat.setString(1, Woonplaats);
            prepStat.setString(2, Straatnaam);
            prepStat.setInt(3, Huisnummer);
            prepStat.setString(4, persoon.getId());

            prepStat.executeUpdate();

            stat.close();

        } catch (SQLException exc) {
            JOptionPane.showMessageDialog(this, "Wijzigingen voor persoon niet opgeslagen\n" + exc.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txfVoornaam = new javax.swing.JTextField();
        txfTussenvoegsel = new javax.swing.JTextField();
        txfAchternaam = new javax.swing.JTextField();
        txfWoonplaats = new javax.swing.JTextField();
        txfStraatnaam = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txfHuisnummer = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Voornaam:");

        jLabel3.setText("Tussenvoegsel");

        jLabel4.setText("Achternaam");

        jLabel5.setText("Woonplaats");

        jLabel6.setText("Straatnaam");

        jLabel7.setText("Huisnummer");

        jLabel8.setText("Klant Wijzigen");

        jButton1.setText("Wijzigen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txfStraatnaam)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addGap(66, 66, 66))
                        .addComponent(txfVoornaam)
                        .addComponent(txfTussenvoegsel)
                        .addComponent(txfAchternaam)
                        .addComponent(txfWoonplaats)
                        .addComponent(txfHuisnummer)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfVoornaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txfTussenvoegsel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txfAchternaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txfWoonplaats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txfStraatnaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txfHuisnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        wijzigPersoonGegevens();
        wijzigKlantGegevens();
        this.setVisible(false);
        this.persoonFrame.vulPersoonTabelMetKlanten();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txfAchternaam;
    private javax.swing.JTextField txfHuisnummer;
    private javax.swing.JTextField txfStraatnaam;
    private javax.swing.JTextField txfTussenvoegsel;
    private javax.swing.JTextField txfVoornaam;
    private javax.swing.JTextField txfWoonplaats;
    // End of variables declaration//GEN-END:variables
}
